# Generated by Django 4.2.1 on 2023-07-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyFormsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_pas', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('offi_loc', models.CharField(choices=[('Downtown - 1040 SW 2nd Ave, Ocala FL 34471', 'Downtown - 1040 SW 2nd Ave, Ocala FL 34471'), ('Ocala West - 10230 SW 86th Circle, Ocala FL 34481', 'Ocala West - 10230 SW 86th Circle, Ocala FL 34481')], max_length=100)),
                ('sel_pro', models.CharField(choices=[('Ram Vasudevan, MD, FACC, FACP, FCCP, ...', 'Ram Vasudevan, MD, FACC, FACP, FCCP, ...'), ('Punwattie Ramnaraine, FNP-BC', 'Punwattie Ramnaraine, FNP-BC'), ('Alceha Mayne-Thomas, ARNP', 'Alceha Mayne-Thomas, ARNP'), ('Junaina Dominic, PA-C', 'Junaina Dominic, PA-C'), ('Emily Hawkins, APRN, NP-C', 'Emily Hawkins, APRN, NP-C'), ('Amreen Noorani, ARNP', 'Amreen Noorani, ARNP')], max_length=100)),
                ('Avail_date', models.DateField()),
                ('Av_date_best_time', models.CharField(choices=[(' 8 AM - 10 AM', ' 8 AM - 10 AM'), ('10 AM - 12 Noon', '10 AM - 12 Noon'), (' 12 Noon - 2 PM', ' 12 Noon - 2 PM'), (' 2 PM - 4 PM', ' 2 PM - 4 PM')], max_length=20)),
                ('Alter_date', models.DateField()),
                ('Al_date_best_time', models.CharField(choices=[(' 8 AM - 10 AM', ' 8 AM - 10 AM'), ('10 AM - 12 Noon', '10 AM - 12 Noon'), (' 12 Noon - 2 PM', ' 12 Noon - 2 PM'), (' 2 PM - 4 PM', ' 2 PM - 4 PM')], max_length=20)),
                ('select_insu', models.CharField(choices=[('No Insurance', 'No Insurance'), ('Other Insurance', 'Other Insurance'), ('Aetna', 'Aetna'), ('Anthem', 'Anthem'), ('Blue Cross Blue Sheld', 'Blue Cross Blue Sheld'), ('Care Plus', 'Care Plus'), ('Cigna', 'Cigna'), ('Humana', 'Humana'), ('Medicaid', 'Medicaid'), ('Medicare', 'Medicare'), ('UnitedHealth Care', 'UnitedHealth Care')], max_length=100)),
                ('insu_mem_id', models.CharField(max_length=20)),
                ('insu_grp_id', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('how_did_you', models.CharField(choices=[('Insurance Provider', 'Insurance Provider'), ('Google', 'Google'), ('Bing', 'Bing'), ('Yahoo', 'Yahoo'), ('Yelp', 'Yelp'), ('Healthgrades', 'Healthgrades'), ('Friend / Collegue', 'Friend / Collegue'), ('Local Advertisement', 'Local Advertisement'), ('Other', 'Other')], max_length=100)),
            ],
        ),
    ]
