# Generated by Django 4.2.1 on 2023-08-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='canonical_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='follow',
            field=models.CharField(blank=True, choices=[('follow', 'Follow'), ('nofollow', 'Nofollow')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='robots',
            field=models.CharField(blank=True, choices=[('index', 'Index'), ('noindex', 'Noindex')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='schema',
            field=models.TextField(blank=True, null=True),
        ),
    ]
