# Generated by Django 4.2.1 on 2023-06-15 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_ourmission_services_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='alt_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='canonical_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='follow',
            field=models.CharField(blank=True, choices=[('follow', 'Follow'), ('nofollow', 'Nofollow')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='robots',
            field=models.CharField(blank=True, choices=[('index', 'Index'), ('noindex', 'Noindex')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='schema',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='alt_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='canonical_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='follow',
            field=models.CharField(blank=True, choices=[('follow', 'Follow'), ('nofollow', 'Nofollow')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='robots',
            field=models.CharField(blank=True, choices=[('index', 'Index'), ('noindex', 'Noindex')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='schema',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('robots', models.CharField(blank=True, choices=[('index', 'Index'), ('noindex', 'Noindex')], max_length=10, null=True)),
                ('follow', models.CharField(blank=True, choices=[('follow', 'Follow'), ('nofollow', 'Nofollow')], max_length=10, null=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('schema', models.TextField(blank=True, null=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.pages')),
            ],
        ),
    ]
